[build]
command = "pnpm build"
publish = ".next"

[functions]
node_bundler = "esbuild"
external_node_modules = []

[[plugins]]
package = "@netlify/plugin-nextjs"

[[scheduled_functions]]
name = "reminders"
schedule = "0 3 * * *"

[[scheduled_functions]]
name = "reconcile-sumup"
schedule = "10 3 * * *"
